### ISSUE TITLE
Intro web clojure の最終目標をとりあえず TODO アプリにする

### ISSUE THREAD

**Issue by ayato-p** [ayato-p/clojure-beginner#5]
書きながら最終目標がないのに Web アプリ作る説明っていうのもつらい気がしたので目標を定めてゴールに向かっていきながら Webアプリに必要なものを説明していきたい。
- [x] 目標を TODO アプリ作ることにして若干書き直し
- [x] Ring について書く(この中で reload ミドルウェアとかくらいは入れておく? 順番としては reload ミドルウェアがなくても再評価によって出力結果が変わることを確認するくらいはした後)
- [x] Compojure を使ったルーティングの書き方を書く
- [x] 開発用ミドルウェアについて書く( reload ミドルウェアと prone /ついでに environ 突っ込んだ )
- [x] テンプレートエンジンについて書く( Hiccup is better? )
- [x] データベース層について書く(最初は直接 SQL を書いて jdbc を直接使う? Yesql と Honeysql ? 複雑度が低いので Honeysql でいいかもしれない)
- [x] ここまでで一度作ってない画面を作っていく( CSRF とかフォームパラメーターとかの取り扱いを書いてないので)
- [ ] ユーザー認証系? buddy?
- [ ] この辺で便利なものに色々切り替えていく?
- [ ] ring-jetty-adapter -> immutant?
- [ ] compojure to bidi? 
- [ ] jdbc direct -> dsl? or yesql? (dil is suricatta or stch-library.sql or honeysql)
- [ ] clojurescript with good middleware
- [ ] css ?
- [ ] component?
- [ ] leiningen (というか project.clj ) についてもちょこちょこ何か書いていこう
- [ ] 最終的に色々ライブラリを組み替えることが出来るからフレームワークより組み合わせ可能なライブラリを複数用いるのが好まれるんだよってとこまで説明出来たらかっこよさそう(実装の仕方をちゃんと考えないと強依存になって難しくなるけど…)
- [ ] デバッグや問題解決のヒント?(依存性が衝突したときなど)

何か気付いたら足そう

あとでチェックすること
- [ ] てにをはチェック
- [ ] 何度か読み返す

**Comment by ayato-p** [comment]
というか、これ作るのも結構大変だな。
